// ==UserScript==
// @name         Supabase 中文汉化插件
// @namespace    https://github.com/RainLin10/supabase-chinese
// @version      0.1.1
// @description  将 Supabase Dashboard 常见英文界面汉化为中文
// @author       OpenVideoMaker
// @match        https://supabase.com/dashboard*
// @match        https://supabase.com/dashboard/*
// @match        https://app.supabase.com/*
// @run-at       document-end
// @grant        none
// ==/UserScript==

(function () {
  "use strict";

  /**
   * Supabase 中文汉化插件
   *
   * 说明：
   * 1. 只替换页面上的可见英文文案，不会读取、上传、修改你的 Supabase 数据。
   * 2. 会尽量避开 SQL 编辑器、代码块、密钥、URL、连接串等敏感内容。
   * 3. Supabase 页面是 React 动态渲染，所以脚本内置 MutationObserver，会自动翻译后续出现的弹窗、菜单、下拉框。
   */

  const DICT = Object.freeze({

    // ============================================================
    // 补充：Database Settings / Advanced Disk / Create Table
    // ============================================================
    "Database Settings": "数据库设置",
    "Connections, security, and network configuration": "连接、安全和网络配置",
    "Database password": "数据库密码",
    "Used for direct Postgres connections": "用于直连 Postgres 的密码",
    "Reset database password": "重置数据库密码",
    "Reset password": "重置密码",
    "The database password isn’t viewable after creation. Resetting it will break any existing connections.": "数据库密码创建后无法查看。重置后，所有现有连接都将失效。",
    "Connection pooling": "连接池",
    "Connection poolers": "连接池服务",
    "Configuration is shared across all connection poolers.": "该配置会在所有连接池服务之间共享。",
    "Connection pool size": "连接池大小",
    "The maximum number of connections made to the underlying Postgres cluster, per user+db combination. Pool size has a default of": "每个“用户 + 数据库”组合可连接到底层 Postgres 集群的最大连接数, 连接池大小默认为",
    "based on your compute size of": " 根据当前规格计算",
    "Max client connections": "最大客户端连接数",
    "The maximum number of concurrent client connections allowed. This value is fixed at": "允许的最大并发客户端连接数: ",
    "based on your compute size of": " 根据当前规格计算",
    "and cannot be changed.": "无法更改",
    "SSL configuration": "SSL 配置",
    "Enforce SSL on incoming connections": "强制传入连接使用 SSL",
    "Reject non-SSL connections to your database": "拒绝连接到数据库的非 SSL 连接",
    "SSL Certificate": "SSL 证书",
    "Use this certificate when connecting to your database to prevent snooping and man-in-the-middle attacks.": "连接数据库时使用此证书，以防止窃听和中间人攻击。",
    "Download certificate": "下载证书",
    "Disk management": "磁盘管理",
    "Disk Management has moved": "磁盘管理已迁移",
    "Disk configuration is now managed alongside Project Compute on the new Compute and Disk page.": "磁盘配置现在已迁移到新的“计算与磁盘”页面，并与项目计算配置一起管理。",
    "Go to Compute and Disk": "前往计算与磁盘",
    "Network restrictions": "网络访问限制",
    "Add restriction": "添加限制",
    "Your database can be accessed by all IP addresses": "当前所有 IP 地址都可以访问你的数据库",
    "You may start limiting access to your database by adding a network restriction.": "你可以通过添加网络限制来开始限制数据库访问。",
    "Restrict all access": "限制所有访问",
    "Network bans": "网络封禁",
    "IP addresses temporarily blocked due to suspicious traffic": "因可疑流量而被临时封禁的 IP 地址",
    "There are no banned IP addresses for your project": "你的项目目前没有被封禁的 IP 地址",

    "Autoscale growth percent": "自动扩容增长百分比",
    "Percentage of current disk size to grow": "按当前磁盘大小增长的百分比",
    "This amounts to 1 GB based on the current disk size of 2 GB": "根据当前 2 GB 的磁盘大小，这相当于增加 1 GB。",
    "Minimum increment": "最小增量",
    "Minimum value to autoscale disk size by": "磁盘自动扩容的最小增量",
    "Maximum disk size": "最大磁盘大小",
    "Maximum size that the disk can grow to": "磁盘可扩展到的最大大小",
    "Disk size will automatically be expanded by 6 GB to a total of 8 GB when the database reaches 90% of the disk size": "当数据库使用量达到磁盘大小的 90% 时，磁盘会自动扩容 6 GB，总容量变为 8 GB。",
    "Adjusting disk configuration requires LARGE Compute size or above": "调整磁盘配置需要 LARGE 或更高计算规格",
    "Increase your compute size to adjust your disk's storage type, IOPS, and throughput": "请提升计算规格后再调整磁盘的存储类型、IOPS 和吞吐量。",
    "Change to LARGE Compute": "切换到 LARGE 计算规格",
    "Storage type": "存储类型",
    "General Purpose SSD": "通用型 SSD",
    "Balance between price and performance": "在价格和性能之间取得平衡",
    "IOPS": "IOPS",
    "Input/output operations per second.": "每秒输入/输出操作次数。",
    "Use higher IOPS for high-throughput apps.": "高吞吐应用建议使用更高 IOPS。",
    "Throughput": "吞吐量",
    "Amount of data read/written per second.": "每秒读取/写入的数据量。",
    "Higher throughput suits applications with high data transfer needs.": "更高吞吐量适合有大量数据传输需求的应用。",

    "Create a new table under": "在以下架构下创建新表",
    "Optional": "可选",
    "Enable Row Level Security (RLS)": "启用行级安全（RLS）",
    "RECOMMENDED": "推荐",
    "Recommended": "推荐",
    "Restrict access to your table by enabling RLS and writing Postgres policies.": "启用 RLS 并编写 Postgres 策略，以限制对表的访问。",
    "Policies are required to query data": "查询数据需要策略",
    "You need to create an access policy before you can query data from this table. Without a policy, querying this table will return an": "你需要先创建访问策略，才能从此表查询数据。如果没有策略，查询此表会返回",
    "array of results. You can create policies after saving this table.": "结果。保存表后可以继续创建策略。",
  
    "empty array": "空数组",
    "Enable Realtime": "启用实时功能",
    "Broadcast changes on this table to authorized subscribers.": "将此表的变更广播给已授权的订阅者。",
    "Default Value": "默认值",
    "Primary": "主键",
    "About data types": "关于数据类型",
    "Import data from CSV": "从 CSV 导入数据",
    "Add column": "添加列",
    "Foreign keys": "外键",
    "Add foreign key relation": "添加外键关系",
    "Data API Access": "Data API 访问",
    "Allow this table to be queried via Supabase client libraries or the API directly": "允许通过 Supabase 客户端库或 API 直接查询此表。",
    "The \"public\" schema is not exposed via the Data API": "\"public\" 架构尚未通过 Data API 暴露",
    "To enable API access for this table, you need to first expose the": "要为此表启用 API 访问，你需要先在",
    "schema in your":" 暴露架构在你的",
    "API settings": "API 设置中",


    // ============================================================
    // 通用：基础词、按钮、状态、表头
    // ============================================================
    "Projects": "项目",
    "Project": "项目",
    "Team": "团队",
    "Integrations": "集成",
    "Usage": "用量",
    "Billing": "账单",
    "Organization Settings": "组织设置",
    "Settings": "设置",
    "General": "常规",
    "Security": "安全",
    "SSO": "单点登录",
    "Single Sign-On": "单点登录",
    "Configuration": "配置",
    "CONFIGURATION": "配置",
    "Connections": "连接",
    "CONNECTIONS": "连接",
    "Compliance": "合规",
    "COMPLIANCE": "合规",
    "Manage": "管理",
    "MANAGE": "管理",
    "Platform": "平台",
    "PLATFORM": "平台",
    "Tools": "工具",
    "TOOLS": "工具",
    "Explore": "浏览",
    "EXPLORE": "浏览",
    "Installed": "已安装",
    "INSTALLED": "已安装",
    "General settings": "常规设置",
    "More information": "更多信息",
    "Documentation": "文档",
    "Docs": "文档",
    "Examples": "示例",
    "Feedback": "反馈",
    "Search...": "搜索...",
    "Search": "搜索",
    "Source": "来源",
    "Primary Database": "主数据库",
    "Primary database": "主数据库",
    "Save": "保存",
    "Save changes": "保存更改",
    "Save Changes": "保存更改",
    "Cancel": "取消",
    "Clear": "清除",
    "Copy": "复制",
    "Reveal": "显示",
    "Refresh": "刷新",
    "Export": "导出",
    "Run": "运行",
    "Apply": "应用",
    "Today": "今天",
    "New": "新建",
    "NEW": "新",
    "BETA": "测试版",
    "ALPHA": "内测版",
    "OFFICIAL": "官方",
    "Official": "官方",
    "PROTECTED": "受保护",
    "Protected": "受保护",
    "Enabled": "已启用",
    "Disabled": "已禁用",
    "Verify Enabled": "启用并验证",
    "Latest": "最新",
    "LATEST": "最新",
    "Status": "状态",
    "STATUS": "状态",
    "Name": "名称",
    "NAME": "名称",
    "Description": "描述",
    "DESCRIPTION": "描述",
    "Role": "角色",
    "ROLE": "角色",
    "Owner": "所有者",
    "Administrator": "管理员",
    "Developer": "开发者",
    "Member": "成员",
    "MEMBER": "成员",
    "MFA": "多因素认证",
    "Email": "邮箱",
    "Email address": "邮箱地址",
    "Additional emails": "其他邮箱",
    "Value": "值",
    "Key": "密钥",
    "Key ID": "密钥 ID",
    "KEY ID": "密钥 ID",
    "Created": "创建时间",
    "CREATED": "创建时间",
    "Created At": "创建时间",
    "CREATED AT": "创建时间",
    "Updated": "更新时间",
    "UPDATED": "更新时间",
    "Actions": "操作",
    "ACTIONS": "操作",
    "Type": "类型",
    "TYPE": "类型",
    "Table": "表",
    "TABLE": "表",
    "View": "视图",
    "Schema": "架构",
    "SCHEMA": "架构",
    "Columns": "列",
    "COLUMNS": "列",
    "Rows": "行",
    "ROWS": "行",
    "Rows processed": "已处理行数",
    "Size": "大小",
    "SIZE": "大小",
    "Realtime": "实时",
    "Auth": "身份认证",
    "Storage": "存储",
    "Database": "数据库",
    "Data API": "数据 API",
    "Edge Functions": "边缘函数",
    "Logs": "日志",
    "Observability": "可观测性",
    "Advisors": "顾问",
    "Advisor": "顾问",
    "Reports": "报告",
    "Templates": "模板",
    "Quickstarts": "快速开始",
    "Community": "社区",
    "COMMUNITY": "社区",
    "Shared": "共享",
    "SHARED": "共享",
    "Favorites": "收藏",
    "FAVORITES": "收藏",
    "Private": "私有",
    "PRIVATE": "私有",
    "Results": "结果",
    "Explain": "解释",
    "Chart": "图表",
    "Insert": "插入",
    "Update": "更新",
    "Delete": "删除",
    "Truncate": "清空",
    "INSERT": "插入",
    "UPDATE": "更新",
    "DELETE": "删除",
    "TRUNCATE": "清空",
    "Request": "请求",
    "Count": "数量",
    "Avg": "平均值",
    "Balance": "余额",
    "Date": "日期",
    "DATE": "日期",
    "Amount": "金额",
    "AMOUNT": "金额",
    "Invoice number": "账单编号",
    "INVOICE NUMBER": "账单编号",
    "Paid": "已支付",
    "PAID": "已支付",
    "No description": "暂无描述",
    "No results found": "未找到结果",
    "No data to show": "暂无数据",
    "Try another search or adjust the filters": "请尝试其他搜索或调整筛选条件",
    "It may take up to 24 hours for data to refresh": "数据刷新可能最多需要 24 小时",
    "Get started for free!": "免费开始使用！",
    "Learn more": "了解更多",
    "Read more": "阅读更多",
    "Show less": "收起",
    "Field Reference": "字段参考",
    "Coming soon": "即将推出",
    "COMING SOON": "即将推出",
    "Early access": "抢先体验",
    "No custom reports yet": "暂无自定义报告",
    "New custom report": "新建自定义报告",
    "Create and save custom reports to track your project metrics": "创建并保存自定义报告，用于跟踪项目指标",
    "Active": "活跃",
    "Inactive": "非活跃",
    "All": "全部",
    "All projects": "所有项目",
    "All Requests": "全部请求",
    "All roles": "全部角色",
    "Active roles": "活跃角色",
    "Alphabetical": "按字母排序",
    "Created At": "创建时间",
    "Current billing cycle": "当前账单周期",
    "Previous billing cycle": "上一个账单周期",
    "This month": "本月",
    "Last hour": "最近 1 小时",
    "Last 10 minutes": "最近 10 分钟",
    "Last 30 minutes": "最近 30 分钟",
    "Last 60 minutes": "最近 60 分钟",
    "Last 3 hours": "最近 3 小时",
    "Last 24 hours": "最近 24 小时",
    "Last 7 days": "最近 7 天",
    "Last 14 days": "最近 14 天",
    "Last 28 days": "最近 28 天",
    "Copy range": "复制范围",

    // ============================================================
    // 项目列表 / 项目概览
    // ============================================================
    "New project": "新建项目",
    "Search for a project": "搜索项目",
    "Sorted by name": "按名称排序",
    "Free Plan": "免费版",
    "FREE": "免费",
    "NANO": "Nano",
    "Healthy": "健康",
    "Last backup": "最近备份",
    "No backups": "暂无备份",
    "Last migration": "最近迁移",
    "No migrations": "暂无迁移",
    "Recent branch": "最近分支",
    "No branches": "暂无分支",
    "Project Overview": "项目概览",
    "Project URL": "项目 URL",
    "Publishable key": "可公开密钥",
    "Direct connection string": "直连字符串",
    "CLI setup commands": "CLI 设置命令",
    "Get connected": "连接项目",
    "Framework": "框架",
    "Use a client library": "使用客户端库",
    "Direct": "直连",
    "Connection string": "连接字符串",
    "ORM": "ORM",
    "Third-party library": "第三方库",
    "MCP": "MCP",
    "Connect your agent": "连接你的智能体",
    "API Keys": "API 密钥",
    "Manage project keys": "管理项目密钥",
    "Total Requests": "总请求数",
    "Database Requests": "数据库请求",
    "Auth Requests": "认证请求",
    "Storage Requests": "存储请求",
    "Realtime Requests": "实时请求",
    "Advisor found no issues": "顾问未发现问题",
    "No security or performance issues found": "未发现安全或性能问题",
    "Ask Assistant": "询问助手",
    "Add block": "添加模块",
    "Build a custom report": "构建自定义报告",
    "Keep track of your most important metrics": "跟踪你最重要的指标",
    "Add your first block": "添加第一个模块",
    "Go to Database Report": "前往数据库报告",

    // ============================================================
    // Team / 邀请成员
    // ============================================================
    "Invite member": "邀请成员",
    "Invite members": "邀请成员",
    "Invite team members": "邀请团队成员",
    "Filter members": "筛选成员",
    "Leave team": "离开团队",
    "Single Sign-On (SSO) available": "可使用单点登录（SSO）",
    "Enforce login via your company identity provider for added security and access control. Available on Team plan and above.": "通过公司身份提供商强制登录，以增强安全性和访问控制。Team 及以上套餐可用。",
    "Upgrade to Team": "升级到 Team",
    "Email addresses": "邮箱地址",
    "Send invitation": "发送邀请",
    "Select provider type": "选择提供商类型",

    // ============================================================
    // Organization Settings / 合规
    // ============================================================
    "General configuration, privacy, and lifecycle controls": "常规配置、隐私和生命周期控制",
    "Organization details": "组织详情",
    "Organization name": "组织名称",
    "Organization slug": "组织短标识",
    "Data privacy": "数据隐私",
    "Supabase Assistant Opt-in Level": "Supabase 助手数据共享级别",
    "Schema Only": "仅架构",
    "Schema & Logs": "架构和日志",
    "Schema, Logs & Database Data": "架构、日志和数据库数据",
    "Supabase AI can provide more relevant answers if you choose to share different levels of data. This feature is powered by third-party AI providers. This is an organization-wide setting, so please select the level of data you are comfortable sharing.": "如果你选择共享不同级别的数据，Supabase AI 可以提供更相关的回答。该功能由第三方 AI 提供商支持。这是组织级设置，请选择你能接受共享的数据级别。",
    "For organizations with HIPAA compliance enabled in their Supabase configuration, any consented information will only be shared with third-party AI providers with whom Supabase has established a Business Associate Agreement (BAA).": "对于已在 Supabase 配置中启用 HIPAA 合规的组织，任何经同意共享的信息只会提供给与 Supabase 签署了商业伙伴协议（BAA）的第三方 AI 提供商。",
    "You do not consent to sharing any database information with third-party AI providers and understand that responses will be generic and not tailored to your database": "你不同意与第三方 AI 提供商共享任何数据库信息，并理解回答将是通用的，不会根据你的数据库定制。",
    "You consent to sharing your database’s schema metadata (such as table and column names, data types, and relationships—but not actual database data) with third-party AI providers": "你同意与第三方 AI 提供商共享数据库架构元数据，例如表名、列名、数据类型和关系，但不包括实际数据库数据。",
    "You consent to sharing your schema and logs (which may contain PII/database data) with third-party AI providers for better results": "你同意与第三方 AI 提供商共享架构和日志（其中可能包含个人信息或数据库数据），以获得更好的结果。",
    "You consent to give third-party AI providers full access to run database read-only queries and analyze results for optimal results": "你同意允许第三方 AI 提供商以只读方式查询数据库并分析结果，以获得最佳回答。",
    "Learn more about data privacy": "了解更多数据隐私信息",
    "Danger zone": "危险区域",
    "Deleting this organization will also remove its projects": "删除该组织也会删除其项目",
    "Make sure you have made a backup of your projects if you want to keep your data": "如果你想保留数据，请确保已经备份项目",
    "Delete organization": "删除组织",
    "Organization-wide security controls and MFA enforcement": "组织级安全控制和 MFA 强制策略",
    "Organization MFA enforcement is not available on Free Plan": "免费版不支持组织级 MFA 强制策略",
    "Upgrade to Pro or above to enforce MFA requirements for your organization.": "升级到 Pro 或更高套餐后可为组织强制启用 MFA。",
    "Upgrade to Pro": "升级到 Pro",
    "SAML SSO configuration and domain access controls": "SAML SSO 配置和域名访问控制",
    "Organization Single Sign-on (SSO) is available from Team plan and above": "组织单点登录（SSO）从 Team 套餐起可用",
    "SSO as a login option provides additional account security for your team by enforcing the use of an identity provider when logging into Supabase. Upgrade to Team or above to set up SSO for your organization.": "SSO 作为登录选项，可通过强制使用身份提供商登录 Supabase 来提升团队账号安全性。升级到 Team 或更高套餐后，可为组织设置 SSO。",
    "OAuth Apps": "OAuth 应用",
    "Published and authorized OAuth applications": "已发布和已授权的 OAuth 应用",
    "Published apps": "已发布应用",
    "Build integrations that extend Supabase's functionality": "构建扩展 Supabase 功能的集成",
    "Publish OAuth app": "发布 OAuth 应用",
    "Authorized apps": "已授权应用",
    "Applications that have access to your organization's settings and projects": "可以访问你组织设置和项目的应用",
    "You do not have any published applications yet": "你还没有任何已发布应用",
    "You do not have any authorized applications yet": "你还没有任何已授权应用",
    "Audit Logs": "审计日志",
    "Organization-level activity history and security event records": "组织级活动历史和安全事件记录",
    "Organization Audit Logs are not available on Free or Pro plans": "Free 或 Pro 套餐不支持组织审计日志",
    "Upgrade to Team or Enterprise to view up to 62 days of Audit Logs for your organization.": "升级到 Team 或 Enterprise 后可查看组织最多 62 天的审计日志。",
    "Legal Documents": "法律文档",
    "Compliance documentation and legal agreements": "合规文档和法律协议",
    "Data Processing Addendum (DPA)": "数据处理附录（DPA）",
    "All organizations can sign our Data Processing Addendum (“DPA”) as part of their GDPR compliance.": "所有组织都可以签署我们的数据处理附录（DPA），作为 GDPR 合规的一部分。",
    "You can review a static PDF version of our latest DPA document here.": "你可以在这里查看我们最新版 DPA 文档的静态 PDF 版本。",
    "Request DPA": "申请 DPA",
    "Transfer Impact Assessment (TIA)": "传输影响评估（TIA）",
    "All organizations can access and use our TIA as part of their GDPR-compliant data transfer process.": "所有组织都可以访问并使用我们的 TIA，作为符合 GDPR 的数据传输流程的一部分。",
    "Download TIA": "下载 TIA",
    "SOC2 Type 2": "SOC2 Type 2",
    "Organizations on Team Plan or above have access to our most recent SOC2 Type 2 report.": "Team 及以上套餐的组织可以访问我们最新的 SOC2 Type 2 报告。",
    "ISO 27001": "ISO 27001",
    "Organizations on Team Plan or above have access to our most recent ISO 27001 certificate.": "Team 及以上套餐的组织可以访问我们最新的 ISO 27001 证书。",
    "HIPAA": "HIPAA",
    "This is only for HIPAA requests. Please ignore this if you already have HIPAA enabled.": "这仅用于 HIPAA 申请。如果你已经启用了 HIPAA，请忽略此项。",
    "Organizations on the Team Plan or above are eligible for a paid HIPAA compliance add-on. You can submit a request here and we will get back to you on the pricing and process for your use case.": "Team 及以上套餐的组织可申请付费 HIPAA 合规附加组件。你可以在这里提交申请，我们会根据你的使用场景回复价格和流程。",
    "Organizations on the Free or Pro Plan can also submit a request for HIPAA. Note that you are still required to upgrade to the Team Plan after your request is approved.": "Free 或 Pro 套餐的组织也可以提交 HIPAA 申请。请注意，申请获批后仍需升级到 Team 套餐。",
    "Request HIPAA": "申请 HIPAA",
    "Standard Security Questionnaire": "标准安全问卷",
    "Organizations on Team Plan or above have access to our standard security questionnaire.": "Team 及以上套餐的组织可以访问我们的标准安全问卷。",
    "Submit a support request": "提交支持请求",

    // ============================================================
    // 组织集成 / Billing / Usage
    // ============================================================
    "GitHub Connections": "GitHub 连接",
    "GitHub Integration": "GitHub 集成",
    "Connect any of your GitHub repositories to a project.": "将你的任意 GitHub 仓库连接到项目。",
    "How do GitHub connections work?": "GitHub 连接如何工作？",
    "How does the GitHub integration work?": "GitHub 集成如何工作？",
    "Connect a GitHub repository to a Supabase project. The GitHub app watches file, branch, and pull request activity in your repository.": "将 GitHub 仓库连接到 Supabase 项目。GitHub 应用会监听仓库中的文件、分支和拉取请求活动。",
    "Connecting to GitHub allows you to sync preview branches with a chosen GitHub branch, keep your production branch in sync, and automatically create preview branches for every pull request.": "连接 GitHub 后，你可以将预览分支与指定 GitHub 分支同步，保持生产分支同步，并为每个拉取请求自动创建预览分支。",
    "Add new project connection": "添加新的项目连接",
    "Authorize with GitHub": "使用 GitHub 授权",
    "Connect your GitHub account to access and select repositories for integration.": "连接你的 GitHub 账号，以访问并选择要集成的仓库。",
    "Authorize GitHub": "授权 GitHub",
    "Vercel Integration": "Vercel 集成",
    "Connect your Vercel teams to your Supabase organization.": "将你的 Vercel 团队连接到 Supabase 组织。",
    "How does the Vercel integration work?": "Vercel 集成如何工作？",
    "Supabase will keep your environment variables up to date in each of the projects you assign to a Supabase project. You can also link multiple Vercel projects to the same Supabase project.": "Supabase 会让你分配给 Supabase 项目的每个 Vercel 项目中的环境变量保持最新。你也可以将多个 Vercel 项目链接到同一个 Supabase 项目。",
    "Install Vercel Integration": "安装 Vercel 集成",
    "AWS PrivateLink": "AWS PrivateLink",
    "Connect to your Supabase project from your AWS VPC using AWS PrivateLink.": "使用 AWS PrivateLink 从 AWS VPC 连接到 Supabase 项目。",
    "How does the AWS PrivateLink integration work?": "AWS PrivateLink 集成如何工作？",
    "Connecting to AWS PrivateLink allows you to create a private connection between your AWS VPC and your Supabase project.": "连接 AWS PrivateLink 后，可以在你的 AWS VPC 与 Supabase 项目之间创建私有连接。",
    "Only available on Team or Enterprise Plan and above": "仅 Team 或 Enterprise 及以上套餐可用",
    "Connect your AWS VPC privately to your Supabase project using AWS PrivateLink.": "使用 AWS PrivateLink 将 AWS VPC 私有连接到 Supabase 项目。",
    "Add account": "添加账号",
    "No accounts connected": "暂无已连接账号",

    "Usage Summary": "用量摘要",
    "Organization is on the Free Plan": "组织当前使用免费版",
    "You have not exceeded your Free Plan quota in this billing cycle.": "你在当前账单周期内尚未超出免费版额度。",
    "Your plan includes a limited amount of usage. If exceeded, you may experience restrictions, as you are currently not billed for overages. It may take up to 1 hour to refresh.": "你的套餐包含有限的使用额度。如果超出额度，由于你当前不会为超额用量付费，项目可能会受到限制。数据刷新最多可能需要 1 小时。",
    "How billing works": "计费方式",
    "Supabase Plans": "Supabase 套餐",
    "Egress": "出站流量",
    "Cached Egress": "缓存出站流量",
    "Database & Storage Size": "数据库与存储大小",
    "Database Size": "数据库大小",
    "Storage Size": "存储大小",
    "Activity": "活动",
    "Monthly Active Users": "月活跃用户",
    "Monthly Active Third-Party Users": "第三方认证月活跃用户",
    "Monthly Active SSO Users": "月活跃 SSO 用户",
    "Storage Image Transformations": "存储图片转换",
    "Edge Function Invocations": "边缘函数调用",
    "Realtime Messages": "实时消息",
    "Realtime Concurrent Peak Connections": "实时并发峰值连接数",
    "Not included in plan": "当前套餐不包含",
    "Unavailable in plan": "当前套餐不可用",
    "Upgrade plan": "升级套餐",
    "Manage Database Size": "管理数据库大小",
    "You need to be on a higher plan in order to use this feature.": "你需要升级到更高套餐才能使用此功能。",
    "Included in Free Plan": "免费版包含",
    "Included in plan": "套餐内包含",
    "Used in period": "周期内已使用",
    "Overage in period": "周期内超额用量",
    "Egress usage": "出站流量用量",
    "Cached Egress usage": "缓存出站流量用量",
    "Database Size usage": "数据库大小用量",
    "Storage Size usage": "存储大小用量",
    "Monthly Active Users usage": "月活跃用户用量",
    "Monthly Active Third-Party Users usage": "第三方认证月活跃用户用量",
    "Monthly Active SSO Users usage": "SSO 月活跃用户用量",
    "Storage Image Transformations usage": "存储图片转换用量",
    "Edge Function Invocations usage": "边缘函数调用用量",
    "Realtime Messages usage": "实时消息用量",
    "Realtime Concurrent Peak Connections usage": "实时并发峰值连接用量",
    "Egress per day": "每日出站流量",
    "Cached Egress per day": "每日缓存出站流量",
    "Average Storage Size per day": "每日平均存储大小",
    "Disk Size per day": "每日磁盘大小",
    "Edge Function Invocations per day": "每日边缘函数调用",
    "Realtime Messages per day": "每日实时消息",
    "Max Realtime Concurrent Peak Connections per day": "每日实时并发峰值连接数",
    "The data refreshes every hour.": "数据每小时刷新一次。",
    "The data refreshes every 6 hours.": "数据每 6 小时刷新一次。",
    "The data refreshes every 24 hours.": "数据每 24 小时刷新一次。",
    "The breakdown of different egress types is inclusive of cached egress, even though it is billed separately. The data refreshes every hour.": "不同出站流量类型的明细包含缓存出站流量，尽管它会单独计费。数据每小时刷新一次。",
    "No data in period": "该周期内暂无数据",
    "May take up to 24 hours to show": "可能最多需要 24 小时才会显示",
    "Amount of data transmitted over all network connections": "所有网络连接传输的数据量",
    "Contains any outgoing traffic including Database, Storage, Realtime, Auth, API, Edge Functions, Pooler and Log Drains.": "包含所有出站流量，包括数据库、存储、实时服务、认证、API、边缘函数、连接池和日志导出。",
    "Billing is based on the total sum of uncached egress in GB throughout your billing period.": "计费基于整个账单周期内未缓存出站流量的总 GB 数。",
    "Egress via cache hits is billed separately.": "缓存命中的出站流量会单独计费。",
    "Contains any outgoing traffic that is served from a cache hit. Includes API, Storage and Edge Functions.": "包含所有由缓存命中提供的出站流量，包括 API、存储和边缘函数。",
    "Billing is based on the total sum of cached egress in GB throughout your billing period.": "计费基于整个账单周期内缓存出站流量的总 GB 数。",
    "Amount of resources your project is consuming": "项目正在消耗的资源量",
    "Database size refers to the actual amount of space used by all your database objects, as reported by Postgres.": "数据库大小指 Postgres 报告的所有数据库对象实际占用空间。",
    "Sum of all objects in your storage buckets.": "所有存储桶中对象的总大小。",
    "Billing is prorated down to the hour and will be displayed GB-Hrs.": "计费会按小时折算，并以 GB-Hrs 显示。",
    "Usage statistics that reflect the activity of your project": "反映项目活动情况的用量统计",
    "Users who log in or refresh their token count towards MAU.": "登录或刷新令牌的用户会计入 MAU。",
    "Billing is based on the sum of distinct users requesting your API throughout the billing period. Resets every billing cycle.": "计费基于整个账单周期内请求你 API 的去重用户总数。每个账单周期会重置。",
    "SSO users who log in or refresh their token count towards SSO MAU.": "通过 SSO 登录或刷新令牌的用户会计入 SSO MAU。",
    "Billing is based on the sum of distinct Single-Sign-On users requesting your API throughout the billing period. Resets every billing cycle.": "计费基于整个账单周期内请求你 API 的去重单点登录用户总数。每个账单周期会重置。",
    "We count all images that were transformed in the billing period, ignoring any transformations.": "我们统计账单周期内发生过转换的所有图片，不重复计算同一图片的不同转换规格。",
    "Usage example: You transform one image with four different size transformations and another image with just a single transformation. It counts as two images were transformed.": "使用示例：一张图片转换了 4 种不同尺寸，另一张图片只转换了 1 次，最终会按 2 张已转换图片计算。",
    "Billing is based on the count of (origin) images that used transformations throughout the billing period. Resets every billing cycle.": "计费基于整个账单周期内使用过图片转换的原始图片数量。每个账单周期会重置。",
    "Every serverless function invocation independent of response status is counted.": "每次无服务器函数调用都会被计数，不受响应状态影响。",
    "Billing is based on the sum of all invocations throughout your billing period.": "计费基于整个账单周期内所有调用次数总和。",
    "Count of messages going through Realtime. Includes database changes, broadcast and presence.": "通过实时服务传递的消息数量，包括数据库变更、广播和在线状态消息。",
    "Usage example: If you do a database change and 5 clients listen to that change via Realtime, that's 5 messages. If you broadcast a message and 4 clients listen to that, that's 4 messages.": "使用示例：如果你进行一次数据库变更，并有 5 个客户端通过 Realtime 监听该变更，则计为 5 条消息。如果你广播一条消息，并有 4 个客户端接收，则计为 4 条消息。",
    "Billing is based on the total amount of messages throughout your billing period.": "计费基于整个账单周期内的实时消息总数。",
    "Total number of successful connections. Connections attempts are not counted towards usage.": "成功连接的总数。连接尝试不会计入用量。",
    "Billing is based on the maximum amount of concurrent peak connections throughout your billing period.": "计费基于整个账单周期内的最大并发峰值连接数。",
    "Current database size per project": "当前每个项目的数据库大小",
    "Current disk size per project": "当前每个项目的磁盘大小",
    "Cumulative Monthly Active Users in billing period": "账单周期内累计月活跃用户",
    "Cumulative Monthly Active Third-Party Users in billing period": "账单周期内累计第三方认证月活跃用户",
    "Cumulative Monthly Active SSO Users in billing period": "账单周期内累计 SSO 月活跃用户",

    "Subscription Plan": "订阅套餐",
    "Each organization has it's own subscription plan, billing cycle, payment methods and usage quotas.": "每个组织都有自己的订阅套餐、账单周期、支付方式和用量额度。",
    "Change subscription plan": "更改订阅套餐",
    "This organization is limited by the included usage": "该组织受套餐内用量限制",
    "Projects may become unresponsive when this organization exceeds its included usage quota. To scale seamlessly, upgrade to a paid plan.": "当组织超出套餐内用量额度时，项目可能会变得无响应。若要平滑扩展，请升级到付费套餐。",
    "Cost Control": "费用控制",
    "Allow scaling beyond your plan's included quota.": "允许超出套餐内额度继续扩展使用。",
    "If you need to go beyond the included quota, simply switch off your spend cap to pay for additional usage.": "如果需要超出套餐内额度，只需关闭消费上限，即可为额外用量付费。",
    "Spend cap": "消费上限",
    "Spend cap is enabled": "消费上限已启用",
    "You won't be charged any extra for usage. However, your projects could become unresponsive or enter read only mode if you exceed the included quota.": "你不会因为额外用量被收费。但如果超出套餐内额度，项目可能会无响应或进入只读模式。",
    "Change spend cap": "更改消费上限",
    "Past Invoices": "历史账单",
    "You get an invoice every time you change your plan or when your monthly billing cycle resets.": "每次更改套餐或月度账单周期重置时，你都会收到一张账单。",
    "Payment Methods": "支付方式",
    "Payments for your subscription are made using the default card.": "订阅费用会使用默认银行卡支付。",
    "No payment methods": "暂无支付方式",
    "Add new card": "添加新卡",
    "Credit Balance": "信用余额",
    "Credits will be applied to future invoices, before charging your payment method. This balance includes purchased credits and any prorated credits from plan changes.": "余额会在收取付款方式费用之前抵扣未来账单。该余额包括购买的额度以及套餐变更产生的按比例抵扣额度。",
    "If your credits run out, your default payment method will be charged.": "如果额度用尽，将向你的默认付款方式收费。",
    "Redeem Code": "兑换码",
    "Top Up": "充值",
    "Email Recipient": "账单收件人",
    "All billing correspondence will go to this email": "所有账单相关邮件都会发送到此邮箱",
    "Billing Address & Tax ID": "账单地址与税号",
    "Changes will be reflected in every upcoming invoice, past invoices are not affected": "更改会体现在后续每张账单中，历史账单不受影响。",
    "A Tax ID is only required for registered businesses.": "只有注册企业才需要税号。",
    "Business Tax ID": "企业税号",
    "Select tax ID": "选择税号",

    // ============================================================
    // 项目侧边栏 / Table Editor / SQL Editor
    // ============================================================
    "Table Editor": "表编辑器",
    "SQL Editor": "SQL 编辑器",
    "Authentication": "身份认证",
    "Project Settings": "项目设置",
    "schema": "架构",
    "New table": "新建表",
    "Create a table": "创建表",
    "Design and create a new database table": "设计并创建一个新的数据库表",
    "Search tables...": "搜索表...",
    "No tables or views": "暂无表或视图",
    "Any tables or views you create will be listed here.": "你创建的表或视图会显示在这里。",
    "Recent items": "最近项目",
    "No recent items yet": "暂无最近项目",
    "Items will appear here as you browse through your project": "当你浏览项目时，相关项目会显示在这里。",
    "Find schema...": "查找架构...",
    "Create a new schema": "创建新架构",
    "Show entity types": "显示实体类型",
    "Materialized View": "物化视图",
    "Foreign Table": "外部表",
    "Partitioned Table": "分区表",
    "Search queries...": "搜索查询...",
    "Create a new snippet": "创建新代码片段",
    "Create a new folder": "创建新文件夹",
    "No shared queries": "暂无共享查询",
    "Share queries with your team by right-clicking on the query.": "右键点击查询，即可与团队共享。",
    "No favorite queries": "暂无收藏查询",
    "Save a query to favorites for easy accessibility by clicking the ♡ icon.": "点击 ♡ 图标可将查询加入收藏，方便快速访问。",
    "No private queries created yet": "暂无私有查询",
    "Queries will be automatically saved once you start writing in the editor": "开始在编辑器中编写后，查询会自动保存。",
    "View running queries": "查看正在运行的查询",
    "Click Run to execute your query.": "点击运行来执行查询。",
    "Database role settings": "数据库角色设置",
    "postgres role": "postgres 角色",
    "anon role": "匿名角色",
    "authenticated role": "已认证角色",
    "The default Postgres/superuser role": "默认 Postgres/超级用户角色",
    "This has admin privileges and will bypass Row Level Security (RLS) policies.": "该角色拥有管理员权限，并会绕过行级安全（RLS）策略。",

    // ============================================================
    // Database
    // ============================================================
    "Database Management": "数据库管理",
    "DATABASE MANAGEMENT": "数据库管理",
    "Schema Visualizer": "架构可视化",
    "Tables": "表",
    "Functions": "函数",
    "Triggers": "触发器",
    "Enumerated Types": "枚举类型",
    "Extensions": "扩展",
    "Indexes": "索引",
    "Publications": "发布",
    "Roles": "角色",
    "Policies": "策略",
    "Replication": "复制",
    "Backups": "备份",
    "Migrations": "迁移",
    "Wrappers": "外部包装器",
    "Database Webhooks": "数据库 Webhook",
    "Security Advisor": "安全顾问",
    "Performance Advisor": "性能顾问",
    "Query Performance": "查询性能",
    "No tables in schema": "该架构中暂无表",
    "No tables created yet": "尚未创建表",
    "Database Tables": "数据库表",
    "Search for a table": "搜索表",
    "ROWS (ESTIMATED)": "行数（估算）",
    "SIZE (ESTIMATED)": "大小（估算）",
    "No functions created yet": "尚未创建函数",
    "Database Functions": "数据库函数",
    "Search for a function": "搜索函数",
    "Return Type": "返回类型",
    "RETURN TYPE": "返回类型",
    "Arguments": "参数",
    "ARGUMENTS": "参数",
    "Create a new function": "创建新函数",
    "Database Triggers": "数据库触发器",
    "Execute actions automatically when database events occur": "当数据库事件发生时自动执行操作",
    "Event": "事件",
    "Search for a trigger": "搜索触发器",
    "Search for an event trigger": "搜索事件触发器",
    "Add your first trigger": "添加第一个触发器",
    "Make your database reactive. Send updates in realtime, call edge functions, or validate data as it comes in.": "让数据库具备响应能力：实时发送更新、调用边缘函数，或在数据写入时进行校验。",
    "New trigger": "新建触发器",
    "No event triggers yet": "暂无事件触发器",
    "Event triggers run on database-level events like DDL commands.": "事件触发器会在 DDL 命令等数据库级事件上运行。",
    "Database Enumerated Types": "数据库枚举类型",
    "Custom data types that you can use in your database tables or functions": "可在数据库表或函数中使用的自定义数据类型",
    "Search for a type": "搜索类型",
    "Values": "值",
    "VALUES": "值",
    "Create type": "创建类型",
    "No enumerated types created yet": "尚未创建枚举类型",
    "Database Extensions": "数据库扩展",
    "Manage what extensions are installed in your database": "管理数据库中安装的扩展",
    "Search for an extension": "搜索扩展",
    "Version": "版本",
    "VERSION": "版本",
    "Used by": "使用方",
    "USED BY": "使用方",
    "Links": "链接",
    "LINKS": "链接",
    "ENABLED": "已启用",
    "Deprecated": "已弃用",
    "Database Indexes": "数据库索引",
    "Improve query performance against your database": "提升数据库查询性能",
    "Search for an index": "搜索索引",
    "Create index": "创建索引",
    "Index Advisor": "索引顾问",
    "No indexes created yet": "尚未创建索引",
    "Database Publications": "数据库发布",
    "Search for a publication": "搜索发布",
    "System ID": "系统 ID",
    "SYSTEM ID": "系统 ID",
    "Database Roles": "数据库角色",
    "Manage access control to your database through users, groups, and permissions": "通过用户、用户组和权限管理数据库访问控制",
    "Search for a role": "搜索角色",
    "Active connections": "活跃连接",
    "Add role": "添加角色",
    "Roles managed by Supabase": "由 Supabase 管理的角色",
    "Other database roles": "其他数据库角色",
    "User can login": "用户可以登录",
    "User can create roles": "用户可以创建角色",
    "User can create databases": "用户可以创建数据库",
    "User bypasses every row level security policy": "用户会绕过所有行级安全策略",
    "User is a Superuser": "用户是超级用户",
    "User can initiate streaming replication and put the system in and out of backup mode": "用户可以启动流式复制，并让系统进入或退出备份模式",
    "Manage Row Level Security policies for your tables": "管理表的行级安全策略",
    "Filter tables and policies": "筛选表和策略",
    "No tables to create policies for": "暂无可创建策略的表",
    "RLS Policies control per-user access to table rows. Create a table in this schema first before creating a policy.": "RLS 策略用于控制每个用户对表行的访问权限。请先在此架构中创建表，再创建策略。",

    // ============================================================
    // Authentication
    // ============================================================
    "Sign In / Providers": "登录 / 提供商",
    "Configure authentication providers and login methods for your users": "为用户配置身份认证提供商和登录方式",
    "Supabase Auth": "Supabase 认证",
    "Third-Party Auth": "第三方认证",
    "User Signups": "用户注册",
    "Allow new users to sign up": "允许新用户注册",
    "If this is disabled, new users will not be able to sign up to your application": "如果禁用，新用户将无法注册你的应用。",
    "Allow manual linking": "允许手动关联",
    "Enable manual linking APIs for your project": "为项目启用手动关联 API",
    "Allow anonymous sign-ins": "允许匿名登录",
    "Enable anonymous sign-ins for your project": "为项目启用匿名登录",
    "Confirm email": "确认邮箱",
    "Users will need to confirm their email address before signing in for the first time": "用户首次登录前需要确认邮箱地址",
    "Auth Providers": "认证提供商",
    "Authenticate your users through a suite of providers and login methods": "通过多种提供商和登录方式认证用户",
    "Custom Providers": "自定义提供商",
    "Configure OAuth/OIDC providers for this project using your own issuer or endpoints.": "使用你自己的签发方或端点为此项目配置 OAuth/OIDC 提供商。",
    "Provider Type": "提供商类型",
    "New Provider": "新建提供商",
    "No custom providers found": "未找到自定义提供商",
    "Billing is based on the number of monthly active users (MAUs) requesting your API throughout the billing period.": "账单会基于账单周期内请求你 API 的月活跃用户数（MAU）计算。",
    "Add an authentication provider": "添加认证提供商",
    "Use third-party authentication systems based on JWTs to access your project.": "使用基于 JWT 的第三方认证系统访问你的项目。",
    "Add provider": "添加提供商",
    "OAuth Server": "OAuth 服务器",
    "Configure your project to act as an identity provider for third-party applications": "将项目配置为第三方应用的身份提供商",
    "Enable the Supabase OAuth Server": "启用 Supabase OAuth 服务器",
    "Enable OAuth server functionality for your project to create and manage OAuth applications.": "为项目启用 OAuth 服务器功能，以创建和管理 OAuth 应用。",
    "User Sessions": "用户会话",
    "Configure settings for user sessions and refresh tokens": "配置用户会话和刷新令牌设置",
    "Refresh Tokens": "刷新令牌",
    "Detect and revoke potentially compromised refresh tokens": "检测并撤销可能泄露的刷新令牌",
    "Prevent replay attacks from potentially compromised refresh tokens.": "防止可能泄露的刷新令牌被重放攻击。",
    "Refresh token reuse interval": "刷新令牌复用间隔",
    "Time interval where the same refresh token can be used multiple times to request for an access token. Recommendation: 10 seconds.": "同一个刷新令牌可多次请求访问令牌的时间窗口。建议：10 秒。",
    "Enforce single session per user": "强制每个用户仅保留一个会话",
    "If enabled, all but a user’s most recently active session will be terminated.": "启用后，除用户最近活跃的会话外，其余会话都会被终止。",
    "Time-box user sessions": "限制用户会话时长",
    "The amount of time before a user is forced to sign in again. Use 0 for never.": "用户被强制重新登录前的时长。填 0 表示永不过期。",
    "Inactivity timeout": "非活跃超时",
    "The amount of time a user needs to be inactive to be forced to sign in again. Use 0 for never.": "用户非活跃多久后需要重新登录。填 0 表示永不过期。",
    "Configuring user sessions is only available on the Pro Plan and above": "用户会话配置仅 Pro 及以上套餐可用",
    "Rate Limits": "速率限制",
    "Safeguard against bursts of incoming traffic to prevent abuse and maximize stability": "防止突发流量滥用，并最大化稳定性",
    "Rate limit for sending emails": "发送邮件速率限制",
    "Number of emails that can be sent per hour from your project": "项目每小时可发送的邮件数量",
    "Rate limit for sending SMS messages": "发送短信速率限制",
    "Number of SMS messages that can be sent per hour from your project": "项目每小时可发送的短信数量",
    "Rate limit for token refreshes": "令牌刷新速率限制",
    "Number of sessions that can be refreshed in a 5 minute interval per IP address": "每个 IP 地址每 5 分钟内可刷新的会话数量",
    "Rate limit for token verifications": "令牌验证速率限制",
    "Number of OTP/Magic link verifications that can be made in a 5 minute interval per IP address": "每个 IP 地址每 5 分钟内可进行的 OTP/魔法链接验证次数",
    "Rate limit for anonymous users": "匿名用户速率限制",
    "Number of anonymous sign-ins that can be made per hour per IP address": "每个 IP 地址每小时可进行的匿名登录次数",
    "Rate limit for sign-ups and sign-ins": "注册和登录速率限制",
    "Number of sign-up and sign-in requests that can be made in a 5 minute interval per IP address": "每个 IP 地址每 5 分钟内可发起的注册和登录请求数量",
    "Number of sign-up and sign-in requests that can be made in a 5 minute interval per IP address (excludes anonymous users)": "每个 IP 地址每 5 分钟内可发起的注册和登录请求数量（不包括匿名用户）",
    "Rate limit for Web3 sign-ups and sign-ins": "Web3 注册和登录速率限制",
    "Number of Web3 sign-up or sign-in requests that can be made per IP address in 5 minutes": "每个 IP 地址每 5 分钟内可发起的 Web3 注册或登录请求数量",
    "IP Address Forwarding": "IP 地址转发",
    "Control how Auth determines source IP address for rate limiting.": "控制 Auth 如何确定用于速率限制的源 IP 地址。",
    "Enable IP address forwarding": "启用 IP 地址转发",
    "Clients can forward end-user IP addresses to Auth for rate limiting when using secret API keys.": "使用私密 API 密钥时，客户端可向 Auth 转发终端用户 IP，用于速率限制。",
    "Multi-Factor Authentication (MFA)": "多因素认证（MFA）",
    "Requires users to provide additional verification factors to authenticate": "要求用户提供额外验证因素进行认证",
    "TOTP (App Authenticator)": "TOTP（身份验证器应用）",
    "Control use of TOTP (App Authenticator) factors": "控制 TOTP（身份验证器应用）因素的使用",
    "Maximum number of per-user MFA factors": "每个用户最多可绑定的 MFA 因素数量",
    "How many MFA factors can be enrolled at once per user.": "每个用户可同时注册的 MFA 因素数量。",
    "SMS MFA": "短信 MFA",
    "Phone": "手机号",
    "Control use of phone factors": "控制手机号因素的使用",
    "Phone OTP Length": "手机 OTP 长度",
    "Number of digits in OTP": "OTP 位数",
    "Phone verification message": "手机验证码消息",
    "To format the OTP code use `{{ .Code }}`": "使用 `{{ .Code }}` 来格式化 OTP 验证码",
    "SMS MFA is only available on the Pro Plan and above": "短信 MFA 仅 Pro 及以上套餐可用",
    "Enhanced MFA Security": "增强 MFA 安全",
    "Limit duration of AAL1 sessions": "限制 AAL1 会话持续时间",
    "A user's session will be terminated unless they verify one of their factors within 15 minutes of initial sign in. Recommendation: ON": "用户初次登录后，如果 15 分钟内未验证任一因素，会话将被终止。建议开启。",
    "URL Configuration": "URL 配置",
    "Configure site URL and redirect URLs for authentication": "配置用于认证的站点 URL 和重定向 URL",
    "Site URL": "站点 URL",
    "Redirect URLs": "重定向 URL",
    "URLs that auth providers are permitted to redirect to post authentication. Wildcards are allowed, for example, https://*.domain.com": "认证完成后，认证提供商允许重定向到的 URL。允许使用通配符，例如 https://*.domain.com",
    "Configure the default redirect URL used when a redirect URL is not specified or doesn't match one from the allow list. This value is also exposed as a template variable in the email templates section. Wildcards cannot be used here.": "配置默认重定向 URL。当未指定重定向 URL，或该 URL 不匹配允许列表时，会使用此 URL。该值也会作为邮件模板中的模板变量暴露。这里不能使用通配符。",
    "Add URL": "添加 URL",
    "No Redirect URLs": "暂无重定向 URL",
    "Auth providers may need a URL to redirect back to": "认证提供商可能需要一个用于跳转回来的 URL",
    "Attack Protection": "攻击防护",
    "Configure security settings to protect your project from attacks": "配置安全设置以保护项目免受攻击",
    "Bot and Abuse Protection": "机器人与滥用防护",
    "Enable Captcha protection": "启用验证码防护",
    "Protect authentication endpoints from bots and abuse.": "保护认证端点免受机器人和滥用攻击。",
    "Prevent use of leaked passwords": "禁止使用已泄露密码",
    "Rejects the use of known or easy to guess passwords on sign up or password change.": "注册或修改密码时，拒绝使用已知泄露或容易猜测的密码。",
    "Configure email provider": "配置邮件提供商",
    "Auth Hooks": "认证钩子",
    "Customize your authentication flow": "自定义认证流程",
    "Hooks": "钩子",
    "Add hook": "添加钩子",
    "Create an auth hook": "创建认证钩子",
    "Use Postgres functions or HTTP endpoints to customize your authentication flow.": "使用 Postgres 函数或 HTTP 端点自定义认证流程。",
    "Add a new hook": "添加新钩子",
    "Track and monitor auth events in your project": "跟踪并监控项目中的认证事件",
    "Write audit logs to the database": "将审计日志写入数据库",
    "When enabled, audit logs are written to the audit_log_entries table. You can disable this to reduce disk usage while still accessing logs through the Auth logs.": "启用后，审计日志会写入 audit_log_entries 表。你可以禁用此项以减少磁盘使用，同时仍可通过 Auth 日志访问日志。",
    "Configure settings to optimize your Auth server's performance": "配置设置以优化 Auth 服务器性能",
    "Only available on the Pro Plan and above": "仅 Pro 及以上套餐可用",
    "Upgrade to the Pro Plan to configure Auth server performance settings.": "升级到 Pro 套餐后可配置 Auth 服务器性能设置。",
    "Request duration": "请求时长",
    "Maximum allowed duration for an Auth request": "Auth 请求允许的最长时间",
    "Requests that exceed this time limit are terminated to help manage server load.": "超过此时间限制的请求会被终止，以帮助管理服务器负载。",
    "Connection management": "连接管理",
    "Allocation strategy": "分配策略",
    "Choose whether to allocate a percentage or a fixed number of connections to the Auth server. We recommend a percentage, as it scales automatically with your instance size.": "选择按百分比或固定数量为 Auth 服务器分配连接。建议使用百分比，因为它会随实例规格自动扩展。",
    "Maximum connections": "最大连接数",
    "The maximum number of connections the Auth server can use under peak load.": "Auth 服务器在峰值负载下可使用的最大连接数。",
    "Connections are not reserved and are returned to Postgres after a short idle period.": "连接不会被保留，短暂空闲后会归还给 Postgres。",

    // ============================================================
    // Storage
    // ============================================================
    "Files": "文件",
    "General file storage for most types of digital content": "适用于大多数数字内容的通用文件存储",
    "Buckets": "存储桶",
    "Vectors": "向量",
    "S3": "S3",
    "Create a file bucket": "创建文件存储桶",
    "Store images, videos, documents, and any other file type.": "存储图片、视频、文档以及其他任意文件类型。",
    "New bucket": "新建存储桶",
    "Enable image transformation": "启用图片转换",
    "Optimize and resize images on the fly.": "动态优化和调整图片大小。",
    "Global file size limit": "全局文件大小限制",
    "Restrict the size of files uploaded across all buckets.": "限制所有存储桶上传文件的大小。",
    "Free Plan has a fixed upload file size limit of 50 MB": "免费版固定上传文件大小限制为 50 MB",
    "Upgrade to Pro Plan for a configurable upload file size limit of 500 GB and unlock image transformations.": "升级到 Pro 后可配置最高 500 GB 的上传限制，并解锁图片转换。",
    "Write policies for each bucket to control access to the bucket and its contents": "为每个存储桶编写策略，以控制对存储桶及其内容的访问。",
    "Create a bucket first to start writing policies": "请先创建存储桶，再开始编写策略",
    "Write policies for the tables under the storage schema directly for greater control": "直接为 storage 架构下的表编写策略，以获得更精细的控制。",
    "No policies created yet": "尚未创建策略",
    "New policy": "新建策略",
    "Purpose-built storage for analytical workloads": "专为分析型工作负载构建的存储",
    "Introducing analytics buckets": "分析存储桶介绍",
    "Analytics buckets are now in private alpha. Expect rapid changes, limited features, and possible breaking updates. Please share feedback as we refine the experience and expand access.": "分析存储桶目前处于私有 Alpha 阶段。可能会快速变化、功能有限，并可能出现破坏性更新。欢迎反馈，帮助我们优化体验并扩大访问范围。",
    "Store large datasets for analytics and reporting.": "存储用于分析和报表的大型数据集。",
    "Purpose-built storage for vector data": "专为向量数据构建的存储",
    "Introducing vector buckets": "向量存储桶介绍",
    "Vector buckets are now in private alpha. Expect rapid changes, limited features, and possible breaking updates. Please share feedback as we refine the experience and expand access.": "向量存储桶目前处于私有 Alpha 阶段。可能会快速变化、功能有限，并可能出现破坏性更新。欢迎反馈，帮助我们优化体验并扩大访问范围。",
    "Store, index, and query your vector embeddings at scale.": "大规模存储、索引并查询向量嵌入。",
    "Share feedback": "分享反馈",
    "S3 Configuration": "S3 配置",
    "Connection": "连接",
    "Connect to your bucket using any S3-compatible service via the S3 protocol": "通过 S3 协议使用任意 S3 兼容服务连接到存储桶",
    "S3 protocol connection": "S3 协议连接",
    "Allow clients to connect to Supabase Storage via the S3 protocol": "允许客户端通过 S3 协议连接 Supabase Storage",
    "Endpoint": "端点",
    "Region": "区域",
    "Access keys": "访问密钥",
    "Manage your access keys for this project": "管理此项目的访问密钥",
    "New access key": "新建访问密钥",
    "No access keys created": "尚未创建访问密钥",
    "There are no access keys associated with your project yet": "此项目还没有关联的访问密钥。",

    // ============================================================
    // Edge Functions
    // ============================================================
    "Functions": "函数",
    "Secrets": "密钥",
    "Run server-side logic close to your users": "在靠近用户的位置运行服务端逻辑",
    "Deploy a new function": "部署新函数",
    "Deploy your first edge function": "部署你的第一个边缘函数",
    "Via Editor": "通过编辑器",
    "Create and edit functions directly in the browser. Download to local at any time.": "直接在浏览器中创建和编辑函数，可随时下载到本地。",
    "Open Editor": "打开编辑器",
    "AI Assistant": "AI 助手",
    "Let our AI assistant help you create functions. Perfect for kickstarting a function.": "让 AI 助手帮你创建函数，非常适合快速启动一个函数。",
    "Open Assistant": "打开助手",
    "Via CLI": "通过 CLI",
    "Create and deploy functions using the Supabase CLI. Ideal for local development and version control.": "使用 Supabase CLI 创建和部署函数，适合本地开发和版本控制。",
    "View CLI Instructions": "查看 CLI 指引",
    "Start with a template": "从模板开始",
    "Simple Hello World": "简单 Hello World",
    "Basic function that returns a JSON response": "返回 JSON 响应的基础函数",
    "Supabase Database Access": "访问 Supabase 数据库",
    "Example using Supabase client to query your database": "使用 Supabase 客户端查询数据库的示例",
    "Supabase Storage Upload": "Supabase 存储上传",
    "Upload files to Supabase Storage": "上传文件到 Supabase Storage",
    "Node Built-in API Example": "Node 内置 API 示例",
    "Example using Node.js built-in crypto and http modules": "使用 Node.js 内置 crypto 和 http 模块的示例",
    "Express Server": "Express 服务器",
    "Example using Express.js for routing": "使用 Express.js 路由的示例",
    "Stream text with AI SDK": "使用 AI SDK 流式输出文本",
    "Generate and stream text with Vercel AI SDK": "使用 Vercel AI SDK 生成并流式输出文本",
    "Generate recipes with AI SDK": "使用 AI SDK 生成食谱",
    "Generate structured cooking recipes with Vercel AI SDK": "使用 Vercel AI SDK 生成结构化食谱",
    "Stripe Webhook Example": "Stripe Webhook 示例",
    "Handle Stripe webhook events securely": "安全处理 Stripe Webhook 事件",
    "Send Emails": "发送邮件",
    "Send emails using the Resend API": "使用 Resend API 发送邮件",
    "Image Transformation": "图片转换",
    "Transform images using ImageMagick WASM": "使用 ImageMagick WASM 转换图片",
    "WebSocket Server Example": "WebSocket 服务器示例",
    "Create a real-time WebSocket server": "创建实时 WebSocket 服务器",
    "Edge Function Secrets": "边缘函数密钥",
    "Manage encrypted values for your functions": "管理函数使用的加密值",
    "Add or replace secrets": "添加或替换密钥",
    "ADD OR REPLACE SECRETS": "添加或替换密钥",
    "Add another": "再添加一个",
    "Insert or update multiple secrets at once by pasting key-value pairs": "粘贴键值对即可一次插入或更新多个密钥。",
    "No secrets created": "尚未创建密钥",
    "This project has no custom secrets yet.": "此项目还没有自定义密钥。",
    "default secrets are still available.": "默认密钥仍然可用。",

    // ============================================================
    // Realtime
    // ============================================================
    "Inspector": "检查器",
    "Join a channel": "加入频道",
    "Start listening": "开始监听",
    "Filter messages": "筛选消息",
    "Create realtime experiences": "创建实时体验",
    "Send your first realtime message from your database, application code or edge function": "从数据库、应用代码或边缘函数发送你的第一条实时消息",
    "Set up realtime for me": "帮我设置实时功能",
    "Broadcast messages": "广播消息",
    "Send messages to a channel from your client application or database via triggers.": "从客户端应用或数据库通过触发器向频道发送消息。",
    "Write policies": "编写策略",
    "Set up Row Level Security policies to control who can see messages within a channel": "设置行级安全策略，控制谁可以查看频道中的消息。",
    "Subscribe to a channel": "订阅频道",
    "Receive realtime messages in your application by listening to a channel": "通过监听频道在应用中接收实时消息。",
    "Create a trigger": "创建触发器",
    "Write a policy": "编写策略",
    "Control access to your realtime channels": "控制对实时频道的访问",
    "Create policy": "创建策略",
    "API DISABLED": "API 已禁用",
    "No data will be selectable via Supabase APIs as this schema is not exposed. You may configure this in your project’s API settings.": "由于此架构未暴露，无法通过 Supabase API 查询数据。你可以在项目的 API 设置中配置。",
    "Realtime Settings": "实时设置",
    "Configure your project's Realtime settings": "配置项目的实时设置",
    "Enable Realtime service": "启用实时服务",
    "If disabled, no clients will be able to connect and new connections will be rejected": "如果禁用，客户端将无法连接，新连接会被拒绝。",
    "Allow public access to channels": "允许公开访问频道",
    "If disabled, only private channels will be allowed": "如果禁用，则只允许私有频道。",
    "Database connection pool size": "数据库连接池大小",
    "Realtime Authorization uses this database pool to check client access": "实时授权会使用该数据库连接池检查客户端访问权限。",
    "Max concurrent clients": "最大并发客户端数",
    "Sets maximum number of concurrent clients that can connect to your Realtime service": "设置可连接到实时服务的最大并发客户端数。",
    "Max events per second": "每秒最大事件数",
    "Sets maximum number of events per second that can be sent to your Realtime service": "设置每秒可发送到实时服务的最大事件数。",
    "Spend cap needs to be disabled to configure this value": "需要关闭消费上限才能配置此值",
    "Upgrade to the Pro plan first to disable spend cap": "请先升级到 Pro 套餐以关闭消费上限",
    "Max presence events per second": "每秒最大在线状态事件数",
    "Max payload size in KB": "最大载荷大小（KB）",

    // ============================================================
    // Advisors / Observability / Logs
    // ============================================================
    "Moving to the toolbar": "已迁移到工具栏",
    "Advisors are now available in the top toolbar for quicker access across the dashboard.": "顾问功能现在可在顶部工具栏中快速访问。",
    "Try it now": "立即试用",
    "Errors": "错误",
    "Warnings": "警告",
    "Info": "信息",
    "Filter": "筛选",
    "Issue type": "问题类型",
    "Entity/item": "实体/项目",
    "No errors detected": "未检测到错误",
    "Congrats! There are no errors detected for this database": "恭喜！此数据库未检测到错误。",
    "Reset suggestions": "重置建议",
    "Consider resetting the analysis after making any changes": "修改后可考虑重置分析。",
    "Rerun linter": "重新运行检查器",
    "How are these suggestions generated?": "这些建议是如何生成的？",
    "These suggestions use splinter (Supabase Postgres LINTER).": "这些建议使用 splinter（Supabase Postgres LINTER）生成。",
    "Reset report": "重置报告",
    "Consider resetting the analysis after optimizing any queries": "优化查询后可考虑重置分析。",
    "Inspect your database for potential issues": "检查数据库潜在问题",
    "The Supabase CLI comes with a range of tools to help inspect your Postgres instances for potential issues.": "Supabase CLI 提供了一系列工具，可帮助检查 Postgres 实例中的潜在问题。",
    "API Gateway": "API 网关",
    "Requests by Geography": "按地理位置统计请求",
    "Response Errors": "响应错误",
    "Response Speed": "响应速度",
    "Network Traffic": "网络流量",
    "Request Caching": "请求缓存",
    "Add filter": "添加筛选",
    "Attribute Filter": "属性筛选",
    "Comparison": "比较方式",
    "Provide a string": "请输入字符串",
    "Function": "函数",
    "Status Code": "状态码",
    "Execution Time": "执行时间",
    "Region": "区域",
    "Total Edge Function Invocations": "边缘函数调用总数",
    "Edge Function Status Codes": "边缘函数状态码",
    "Edge Function Invocations by Region": "按区域统计边缘函数调用",
    "Available on the Pro Plan and above": "Pro 及以上套餐可用",
    "Monitoring": "监控",
    "Track authentication errors by status code and error type to identify issues and improve user experience.": "按状态码和错误类型跟踪认证错误，以识别问题并改善用户体验。",
    "Monitor sign-in and sign-up performance metrics including average, percentiles, and request counts to ensure optimal authentication speed.": "监控登录和注册性能指标，包括平均值、百分位和请求数，以确保最佳认证速度。",
    "Auth API Gateway": "Auth API 网关",
    "Monitor user activity, sign-ins, sign-ups, and password reset requests to understand how users interact with your authentication system.": "监控用户活动、登录、注册和密码重置请求，以了解用户如何与你的认证系统交互。",
    "Connected Clients": "已连接客户端",
    "Broadcast Events": "广播事件",
    "Presence Events": "在线状态事件",
    "Postgres Changes Events": "Postgres 变更事件",
    "Rate of Channel Joins": "频道加入速率",
    "Message Payload Size": "消息载荷大小",
    "Realtime API Gateway": "实时 API 网关",
    "Logs & Analytics": "日志与分析",
    "Insert source": "插入来源",
    "New logs": "新日志",
    "Get early access": "获取抢先体验",
    "Search collections...": "搜索集合...",
    "Collections": "集合",
    "COLLECTIONS": "集合",
    "Database Operations": "数据库操作",
    "DATABASE OPERATIONS": "数据库操作",
    "Postgres Version Upgrade": "Postgres 版本升级",
    "Queries": "查询",
    "QUERIES": "查询",
    "Create query": "创建查询",
    "Capture your logs": "采集日志",
    "Send logs to your preferred observability or storage platform.": "将日志发送到你偏好的可观测性或存储平台。",
    "Go to Log Drains": "前往日志导出",
    "Save query": "保存查询",
    "No queries created yet": "尚未创建查询",
    "Create and save your queries to use them in your explorer": "创建并保存查询，以便在浏览器中使用。",
    "No results found": "未找到结果",

    // ============================================================
    // Project Settings / Compute / API Keys / JWT / Add-ons
    // ============================================================
    "Compute and Disk": "计算与磁盘",
    "Configure the compute and disk settings for your project.": "配置项目的计算与磁盘设置。",
    "Upgrade to the Pro Plan to configure compute and disk settings.": "升级到 Pro 后可配置计算与磁盘设置。",
    "Compute size": "计算规格",
    "Hardware resources allocated to your Postgres database": "分配给 Postgres 数据库的硬件资源",
    "Show all sizes": "显示全部规格",
    "Disk Size": "磁盘大小",
    "Your plan includes up to 1GB of gp3 storage.": "你的套餐包含最高 1GB 的 gp3 存储。",
    "Autoscaling": "自动扩容",
    "Advanced disk settings": "高级磁盘设置",
    "Specify additional settings for your disk, including autoscaling configuration, IOPS, throughput, and disk type.": "指定磁盘的其他设置，包括自动扩容配置、IOPS、吞吐量和磁盘类型。",
    "Infrastructure": "基础设施",
    "General information regarding your server instance": "服务器实例的常规信息",
    "Management of read replicas has moved": "只读副本管理已迁移",
    "Read replicas is now managed under Replication in the Database section.": "只读副本现在在 Database 的 Replication 中管理。",
    "Go to Replication": "前往复制",
    "Service Versions": "服务版本",
    "Service versions and upgrade eligibility for your provisioned instance.": "已配置实例的服务版本和升级资格。",
    "Auth version": "Auth 版本",
    "PostgREST version": "PostgREST 版本",
    "Postgres version": "Postgres 版本",
    "Infrastructure Activity": "基础设施活动",
    "Activity statistics related to your server instance": "与你的服务器实例相关的活动统计",
    "CPU": "CPU",
    "Max CPU utilization per day": "每日最大 CPU 使用率",
    "Max CPU usage of your server.": "服务器最大 CPU 使用率。",
    "Memory": "内存",
    "Max memory utilization per day": "每日最大内存使用率",
    "Memory usage of your server.": "服务器内存使用量。",
    "You might observe elevated memory usage, even with little to no load. Besides Postgres, a wide range of services are running under the hood resulting in an elevated base memory usage.": "即使几乎没有负载，你也可能看到较高的内存使用率。除了 Postgres，底层还运行着多种服务，因此基础内存占用会更高。",
    "Disk IO Bandwidth": "磁盘 IO 带宽",
    "The disk performance of your workload is determined by the Disk IO bandwidth.": "工作负载的磁盘性能由磁盘 IO 带宽决定。",
    "Smaller compute instances (below 4XL) can burst above their baseline disk throughput and IOPS for short periods of time. Beyond that, the performance reverts to the baseline.": "较小的计算实例（低于 4XL）可以在短时间内突破基准磁盘吞吐量和 IOPS。超过该时间后，性能会回落到基准值。",
    "Disk IO consumed per day": "每日磁盘 IO 消耗",
    "Configure API keys to securely control access to your project": "配置 API 密钥以安全控制对项目的访问",
    "Publishable and secret API keys": "可公开和私密 API 密钥",
    "Legacy anon, service_role API keys": "旧版 anon、service_role API 密钥",
    "Your new API keys are here": "新的 API 密钥已上线",
    "We've updated our API keys to better support your application needs.": "我们已经更新 API 密钥，以更好地支持你的应用需求。",
    "Having trouble with the new API keys?": "使用新的 API 密钥遇到问题？",
    "Contact support": "联系支持",
    "New publishable key": "新建可公开密钥",
    "This key is safe to use in a browser if you have enabled Row Level Security (RLS) for your tables and configured policies.": "如果你已为表启用行级安全（RLS）并配置策略，则此密钥可以安全地在浏览器中使用。",
    "Publishable keys can be safely shared publicly": "可公开密钥可以安全地公开分享",
    "Secret keys": "私密密钥",
    "New secret key": "新建私密密钥",
    "These API keys allow privileged access to your project's APIs. Use in servers, functions, workers or other backend components of your application.": "这些 API 密钥允许对项目 API 进行特权访问。请用于服务器、函数、Worker 或其他后端组件。",
    "Disable legacy API keys": "禁用旧版 API 密钥",
    "Make sure you are no longer using your legacy API keys before proceeding.": "继续前请确保你不再使用旧版 API 密钥。",
    "Disable JWT-based API keys": "禁用基于 JWT 的 API 密钥",
    "This key has the ability to bypass Row Level Security. Never share it publicly. If leaked, generate a new JWT secret immediately. Prefer using Secret API keys instead.": "此密钥可以绕过行级安全。绝不要公开分享。如果泄露，请立即生成新的 JWT 密钥。建议改用私密 API 密钥。",
    "JWT Keys": "JWT 密钥",
    "Control the keys used to sign JSON Web Tokens for your project": "控制用于为项目签署 JSON Web Token 的密钥",
    "JWT Signing Keys": "JWT 签名密钥",
    "Legacy JWT Secret": "旧版 JWT 密钥",
    "Create Standby Key": "创建备用密钥",
    "CREATE STANDBY KEY": "创建备用密钥",
    "Set up a new key which you can switch to once it has been picked up by all components of your application.": "设置一个新密钥，待应用所有组件都获取后即可切换使用。",
    "Current key": "当前密钥",
    "CURRENT KEY": "当前密钥",
    "Previous key": "上一个密钥",
    "PREVIOUS KEY": "上一个密钥",
    "Previously used keys": "之前使用过的密钥",
    "These JWT signing keys are still used to verify tokens that are yet to expire. Revoke once all tokens have expired.": "这些 JWT 签名密钥仍用于验证尚未过期的令牌。所有令牌过期后即可撤销。",
    "Legacy JWT secret has been migrated to new JWT Signing Keys": "旧版 JWT 密钥已迁移到新的 JWT 签名密钥",
    "Legacy JWT secret can only be changed by rotating to a standby key and then revoking it. It is used to only verify JSON Web Tokens by Supabase products.": "旧版 JWT 密钥只能通过轮换到备用密钥并撤销旧密钥来更改。它仅用于验证 Supabase 产品中的 JSON Web Token。",
    "This includes the anon and service_role JWT based API keys. Consider switching to publishable and secret API keys to disable them.": "这包括基于 JWT 的 anon 和 service_role API 密钥。建议切换到可公开密钥和私密 API 密钥以禁用它们。",
    "Go to API keys": "前往 API 密钥",
    "Legacy JWT secret (still used)": "旧版 JWT 密钥（仍在使用）",
    "Used only to verify JWTs.": "仅用于验证 JWT。",
    "Access token expiry time": "访问令牌过期时间",
    "How long access tokens are valid for before a refresh token has to be used.": "访问令牌在必须使用刷新令牌之前的有效时长。",
    "Recommendation: 3600 (1 hour).": "建议：3600（1 小时）。",
    "General configuration, domains, ownership, and lifecycle": "常规配置、域名、所有权和生命周期",
    "Project name": "项目名称",
    "Displayed throughout the dashboard.": "会显示在整个控制台中。",
    "Project ID": "项目 ID",
    "Referenced used in APIs and URLs.": "用于 API 和 URL 的引用标识。",
    "Project access": "项目访问",
    "Organization-wide access": "组织范围访问",
    "All 1 organization members can access this project.": "该组织的所有成员都可以访问此项目。",
    "Manage members": "管理成员",
    "Project availability": "项目可用性",
    "Restart or pause your project when performing maintenance": "维护时可重启或暂停项目",
    "Restart project": "重启项目",
    "Your project will not be available for a few minutes.": "项目将有几分钟不可用。",
    "Pause project": "暂停项目",
    "Your project will not be accessible while it is paused.": "项目暂停期间无法访问。",
    "Project usage": "项目用量",
    "Project usage statistics have been moved": "项目用量统计已迁移",
    "You may view your project's usage under your organization's settings": "你可以在组织设置中查看项目用量。",
    "View project usage": "查看项目用量",
    "Custom domains": "自定义域名",
    "Present a branded experience to your users": "为用户提供品牌化体验",
    "Custom domains are a Pro Plan add-on": "自定义域名是 Pro 套餐附加组件",
    "Paid Plans come with free vanity subdomains or Custom Domains for an additional $10/month per domain.": "付费套餐包含免费的个性化子域名；自定义域名需额外支付每个域名每月 10 美元。",
    "Transfer project": "转移项目",
    "Transfer project to another organization": "将项目转移到另一个组织",
    "To transfer projects, the owner must be a member of both the source and target organizations.": "要转移项目，所有者必须同时是源组织和目标组织的成员。",
    "Permanently remove your project and its database": "永久删除项目及其数据库",
    "Deleting this project will also remove your database.": "删除此项目也会删除数据库。",
    "Add-ons": "附加组件",
    "Level up your project with add-ons": "通过附加组件增强你的项目",
    "Dedicated IPv4 address": "专用 IPv4 地址",
    "Reserve a dedicated IPv4 address for your project.": "为项目预留一个专用 IPv4 地址。",
    "Point in time recovery": "时间点恢复",
    "Restore your database to a specific moment in the past.": "将数据库恢复到过去的某个具体时间点。",
    "Custom domain": "自定义域名",
    "Serve your project on your own domain name.": "使用你自己的域名提供项目服务。",
    "About custom domains": "关于自定义域名",
    "About PITR backups": "关于 PITR 备份",
    "About IPv4 deprecation": "关于 IPv4 弃用",
    "Capture your logs, your way": "以你喜欢的方式采集日志",
    "Upgrade to a Pro, Team or Enterprise Plan to send your logs to your preferred platform": "升级到 Pro、Team 或 Enterprise 套餐后，可将日志发送到你偏好的平台。",
    "Pricing": "价格",
    "Log Drains are available as a project Add-On for all Pro, Team, and Enterprise users. Each Log Drain costs $60 per month.": "日志导出作为项目附加组件提供给所有 Pro、Team 和 Enterprise 用户。每个日志导出每月 60 美元。",
    "See our pricing": "查看价格",
    "Connect to your drain": "连接你的日志目标",
    "We offer support for multiple destinations including Datadog, Loki, Sentry or a custom endpoint.": "我们支持多个目标，包括 Datadog、Loki、Sentry 或自定义端点。",
    "Read our documentation": "阅读文档",
    "Don't see your preferred drain? Vote here": "没有看到你想用的日志目标？在这里投票",

    // ============================================================
    // Integrations marketplace
    // ============================================================
    "Extend your database": "扩展你的数据库",
    "Extensions and wrappers that add functionality to your database and connect to external services.": "为数据库添加功能并连接外部服务的扩展和包装器。",
    "Search integrations...": "搜索集成...",
    "Wrappers": "包装器",
    "Postgres Modules": "Postgres 模块",
    "Schedule recurring Jobs in Postgres": "在 Postgres 中安排周期性任务",
    "Lightweight message queue in Postgres": "Postgres 中的轻量级消息队列",
    "Continuously sync your payments, customer, and other data from Stripe to your Postgres database": "持续将 Stripe 的付款、客户和其他数据同步到 Postgres 数据库",
    "Auto-generate an API directly from your database schema": "直接从数据库架构自动生成 API",
    "Application level encryption for your project": "项目级应用加密",
    "Overview": "概览",
    "Docs": "文档",
    "Website": "网站",
    "Built by": "构建方",
    "BUILT BY": "构建方",
    "Required extensions": "所需扩展",
    "The Supabase Data API exposes REST endpoints for your project's databases, including read replicas and load balancers. Configure the API base URL, custom domains, and PostgREST settings for your project.": "Supabase Data API 会为项目数据库暴露 REST 端点，包括只读副本和负载均衡器。你可以为项目配置 API 基础 URL、自定义域名和 PostgREST 设置。",
    "RESTful endpoint for querying and managing your database": "用于查询和管理数据库的 RESTful 端点",
    "Enable Data API": "启用 Data API",
    "When enabled you will be able to use any Supabase client library and PostgREST endpoints with any schema configured in the Settings tab.": "启用后，你可以对 Settings 选项卡中配置的任意架构使用 Supabase 客户端库和 PostgREST 端点。",
    "No schemas can be queried": "没有可查询的架构",
    "With this setting disabled, you will not be able to query any schemas via the Data API.": "禁用此设置后，你将无法通过 Data API 查询任何架构。",
    "You will see errors from the Postgrest endpoint": "你会从 PostgREST 端点看到错误。",
    "Vault is a Postgres extension and accompanying Supabase UI that makes it safe and easy to store encrypted secrets and other data in your database. This opens up a lot of possibilities to use Postgres in ways that go beyond what is available in a stock distribution.": "Vault 是一个 Postgres 扩展，并配套 Supabase UI，可以安全、轻松地在数据库中存储加密密钥和其他数据。这让你能够以超出标准发行版能力的方式使用 Postgres。",
    "Under the hood, the Vault is a table of Secrets and Encryption Keys that are stored using Authenticated Encryption on disk. They are then available in decrypted form through a Postgres view so that the secrets can be used by applications from SQL. Because the secrets are stored on disk encrypted and authenticated, any backups or replication streams also preserve this encryption in a way that can't be decrypted or forged.": "在底层，Vault 是一张由密钥和加密密钥组成的表，磁盘上使用认证加密存储。随后可通过 Postgres 视图以解密形式访问，使应用能够从 SQL 中使用这些密钥。由于密钥在磁盘上以加密且经过认证的方式存储，任何备份或复制流也会保留这种加密，无法被解密或伪造。"
  });

  const PLACEHOLDER_DICT = Object.freeze({
    "Search for a project": "搜索项目",
    "Filter members": "筛选成员",
    "name@example.com, name2@example.com, ...": "name@example.com, name2@example.com, ...",
    "Search for a role": "搜索角色",
    "Search for a publication": "搜索发布",
    "Search for a table": "搜索表",
    "Search for a function": "搜索函数",
    "Search for a trigger": "搜索触发器",
    "Search for an event trigger": "搜索事件触发器",
    "Search for a type": "搜索类型",
    "Search for an extension": "搜索扩展",
    "Search for an index": "搜索索引",
    "Search queries...": "搜索查询...",
    "Search tables...": "搜索表...",
    "Find schema...": "查找架构...",
    "Filter tables and policies": "筛选表和策略",
    "Search custom providers": "搜索自定义提供商",
    "Select tax ID": "选择税号",
    "Add additional recipients": "添加其他收件人",
    "Search collections...": "搜索集合...",
    "Search integrations...": "搜索集成...",
    "Provide a string": "请输入字符串",
    "e.g. 2h, 30m, 7d": "例如：2h、30m、7d",
    "e.g CLIENT_KEY": "例如：CLIENT_KEY",
    "Search for a secret": "搜索密钥",
  });

  const REGEX_RULES = [
    [/^(\d+)\s+member$/, "$1 位成员"],
    [/^(\d+)\s+members$/, "$1 位成员"],
    [/^(\d+)\s+connection$/, "$1 个连接"],
    [/^(\d+)\s+connections$/, "$1 个连接"],
    [/^(\d+)\s+tables$/, "$1 张表"],
    [/^(\d+)\s+table$/, "$1 张表"],
    [/^(\d+)\s+errors$/, "$1 个错误"],
    [/^(\d+)\s+warnings$/, "$1 个警告"],
    [/^(\d+)\s+suggestions$/, "$1 条建议"],
    [/^(\d+)\s+rows$/, "$1 行"],
    [/^(\d+)\s+requests per hour$/, "每小时 $1 次请求"],
    [/^(\d+)\s+requests\/5 min$/, "每 5 分钟 $1 次请求"],
    [/^(\d+)\s+emails\/h$/, "$1 封/小时"],
    [/^(\d+)\s+sms\/h$/, "$1 条短信/小时"],
    [/^(\d+)\s+seconds$/, "$1 秒"],
    [/^(\d+)\s+factors$/, "$1 个因素"],
    [/^(\d+)\s+digits$/, "$1 位"],
    [/^(\d+)\s+clients$/, "$1 个客户端"],
    [/^(\d+)\s+events\/s$/, "$1 事件/秒"],
    [/^No (tables|functions|indexes|enumerated types) created yet$/, (m) => {
      const map = { "tables": "表", "functions": "函数", "indexes": "索引", "enumerated types": "枚举类型" };
      return `尚未创建${map[m[1]]}`;
    }],
    [/^There are no (tables|functions|indexes|enumerated types) found in the schema "([^"]+)"$/, (m) => {
      const map = { "tables": "表", "functions": "函数", "indexes": "索引", "enumerated types": "枚举类型" };
      return `在 "${m[2]}" 架构中没有找到任何${map[m[1]]}`;
    }],
    [/^The "([^"]+)" schema doesn't have any tables\.$/, (m) => `"${m[1]}" 架构中还没有任何表。`],
    [/^Showing (\d+) to (\d+) out of (\d+) invoices$/, "正在显示第 $1 到 $2 条，共 $3 张账单"],
    [/^Last (\d+) minutes$/, "最近 $1 分钟"],
    [/^Last (\d+) hours$/, "最近 $1 小时"],
    [/^Last (\d+) days$/, "最近 $1 天"],
    [/^(\d+)\s*GB memory$/, "$1 GB 内存"],
    [/^Up to ([\d.]+)\s*GB memory$/, "最高 $1 GB 内存"],
    [/^(\d+)-core ARM CPU$/, "$1 核 ARM CPU"],
    [/^Shared CPU$/, "共享 CPU"]
  ];

  const IGNORE_TAGS = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "TEXTAREA", "PRE", "CODE", "KBD", "SAMP"]);

  const SKIP_SELECTOR = [
    ".monaco-editor",
    ".cm-editor",
    ".cm-content",
    ".CodeMirror",
    "textarea",
    "pre",
    "code",
    "kbd",
    "samp",
    "[contenteditable='true']",
    "[role='textbox']",
    "[aria-label='SQL editor']",
    "[data-testid='sql-editor']",
    "[data-testid='monaco-editor']",
    "[data-testid='code-editor']",
  ].join(",");

  function normalizeText(text) {
    return String(text || "")
      .replace(/\u00a0/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function looksSensitiveOrCode(text) {
    const s = normalizeText(text);
    if (!s) return true;
    if (DICT[s] || PLACEHOLDER_DICT[s]) return false;

    if (/https?:\/\//i.test(s)) return true;
    if (/postgres(?:ql)?:\/\//i.test(s)) return true;
    if (/\b(sb_publishable|sb_secret|eyJ|SUPABASE_|JWT|BEGIN|SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\b/.test(s)) return true;
    if (/^[A-Za-z0-9_\-]{24,}$/.test(s)) return true;
    if (/^[a-f0-9-]{24,}$/i.test(s)) return true;
    if (/^[\w.-]+@[\w.-]+\.\w+$/.test(s)) return true;

    return false;
  }

  function applyRegexRules(core) {
    for (const [regex, replacement] of REGEX_RULES) {
      const m = core.match(regex);
      if (!m) continue;
      if (typeof replacement === "function") return replacement(m);
      return core.replace(regex, replacement);
    }
    return null;
  }

  function translateRaw(rawText, dict = DICT) {
    if (!rawText || !rawText.trim()) return rawText;

    const leading = rawText.match(/^\s*/)?.[0] || "";
    const trailing = rawText.match(/\s*$/)?.[0] || "";
    const core = normalizeText(rawText);
    if (!core) return rawText;

    const translated = dict[core] || applyRegexRules(core);
    if (!translated || translated === core) return rawText;

    return leading + translated + trailing;
  }

  function shouldIgnoreTextNode(node) {
    const parent = node.parentElement;
    if (!parent) return true;
    if (IGNORE_TAGS.has(parent.tagName)) return true;
    if (parent.closest(SKIP_SELECTOR)) return true;

    const text = normalizeText(node.nodeValue);
    if (looksSensitiveOrCode(text) && !DICT[text]) return true;

    return false;
  }

  function translateTextNodes(root) {
    if (!root) return;

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        if (shouldIgnoreTextNode(node)) return NodeFilter.FILTER_REJECT;
        if (!node.nodeValue || !node.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });

    const nodes = [];
    let node;
    while ((node = walker.nextNode())) nodes.push(node);

    for (const textNode of nodes) {
      const oldValue = textNode.nodeValue;
      const newValue = translateRaw(oldValue);
      if (newValue !== oldValue) textNode.nodeValue = newValue;
    }
  }

  function translateAttributes(root) {
    if (!root || !root.querySelectorAll) return;

    const attrs = ["placeholder", "title", "aria-label"];
    const selector = attrs.map((attr) => `[${attr}]`).join(",");
    const elements = root.querySelectorAll(selector);

    for (const el of elements) {
      if (el.closest(SKIP_SELECTOR)) continue;

      for (const attr of attrs) {
        if (!el.hasAttribute(attr)) continue;

        const oldValue = el.getAttribute(attr);
        if (!oldValue || looksSensitiveOrCode(oldValue)) continue;

        let newValue = translateRaw(oldValue, PLACEHOLDER_DICT);
        if (newValue === oldValue) newValue = translateRaw(oldValue, DICT);

        if (newValue && newValue !== oldValue) el.setAttribute(attr, newValue);
      }
    }
  }

  function translatePage() {
    if (!document.body) return;

    translateTextNodes(document.body);
    translateAttributes(document.body);

    if (document.title) {
      const newTitle = translateRaw(document.title);
      if (newTitle !== document.title) document.title = newTitle;
    }
  }

  let timer = null;
  function scheduleTranslate() {
    clearTimeout(timer);
    timer = setTimeout(translatePage, 120);
  }

  function startObserver() {
    const observer = new MutationObserver(() => scheduleTranslate());

    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: ["placeholder", "title", "aria-label"]
    });
  }

  function watchUrlChange() {
    let lastUrl = location.href;
    setInterval(() => {
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        scheduleTranslate();
      }
    }, 500);
  }

  translatePage();
  startObserver();
  watchUrlChange();
  window.addEventListener("load", scheduleTranslate);
})();